### ISSUE TITLE
not working when two table has a belongsToMany relationship

### ISSUE THREAD

**Issue by deloz** [elipZis/laravel-cacheable-model#15]
```php
final class Resume extends Model
{
    use Cacheable;

    public function workTypes(): BelongsToMany
    {
        return $this->belongsToMany(WorkType::class)
            ->using(ResumeWorkType::class);
    }
}

final class ResumeWorkType extends Pivot
{
    public $timestamps = false;
    protected $table = self::TABLE;
}


final class WorkType extends Model
{
    use Cacheable;
}
```

The cache for the resume list is not updated when adding or removing a workType from a resume. However, the data in the database tables "resume" and "resume_work_types" have been correctly updated.

The resume list query is not working as expected.

```php
  $rows = Resume::query()->with('workTypes')
            ->orderByDesc('id')
            ->paginate(10);

// loop workTypes
foreach ($row->workTypes as $wt) {
    echo {{ $wt->name }} . '<br>';  // not updated
}
```

**Comment by nea** [comment]
Ahoy

Thanks for the report.
Could you post how you removed/added a type?
I do not scan all relations all the time, as this would be a very heavy overload of dependencies to check when they are „soft“ logically so to say. If I can hook into the process, I will. 
The example would help.


Thanks a lot

**Comment by nea** [comment]
Stale
